# This code was auto generated by AfterShip SDK Generator.
# Do not edit the class manually.
require 'cgi'

module AftershipAPI
  class CourierConnectionApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end

    # get_courier_connections
    # Get courier connection results of multiple courier connections.
    # @param [Hash] opts the optional parameters
    # @option opts [String] :courier_slug Unique courier code.(Example: dhl-api)
    # @option opts [String] :cursor A string representing the cursor value for the current page of results.
    # @option opts [String] :limit Number of courier connections each page contain. (Default: 100, Max: 200)
    # @return [Model::GetCourierConnectionsResponse]
    def get_courier_connections(opts: {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: CourierConnectionApi.get_courier_connections ...'
      end


      # resource path
      local_var_path = "/tracking/2026-01/courier-connections"
      method = :'GET'

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'courier_slug'] = opts[:'courier_slug'] if !opts[:'courier_slug'].nil?
      query_params[:'cursor'] = opts[:'cursor'] if !opts[:'cursor'].nil?
      query_params[:'limit'] = opts[:'limit'] if !opts[:'limit'].nil?
      # header parameters
      header_params = opts[:header_params] || {}

      # http body (model)
      post_body = opts[:body]

      # return_type
      return_type = 'GetCourierConnectionsResponseData'

      new_options = opts.merge(
        :operation => :"CourierConnectionApi.get_courier_connections",
        :header_params => header_params,
        :query_params => query_params,
        :body => post_body,
        :return_type => return_type
      )

      data, _status_code, headers = @api_client.call_api(method, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: CourierConnectionApi#get_courier_connections\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end

      resp = Model::GetCourierConnectionsResponse.new
      resp.data = data
      resp.response_header = headers
      resp
    end

    # post_courier_connections
    # 

    # @param body [Model::PostCourierConnectionsRequest]
    # @param [Hash] opts the optional parameters
    # @return [Model::PostCourierConnectionsResponse]
    def post_courier_connections(body:, opts: {})
      opts[:body] = body
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: CourierConnectionApi.post_courier_connections ...'
      end


      # resource path
      local_var_path = "/tracking/2026-01/courier-connections"
      method = :'POST'

      # query parameters
      query_params = opts[:query_params] || {}
      # header parameters
      header_params = opts[:header_params] || {}

      # http body (model)
      post_body = opts[:body]

      # return_type
      return_type = 'CourierConnection'

      new_options = opts.merge(
        :operation => :"CourierConnectionApi.post_courier_connections",
        :header_params => header_params,
        :query_params => query_params,
        :body => post_body,
        :return_type => return_type
      )

      data, _status_code, headers = @api_client.call_api(method, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: CourierConnectionApi#post_courier_connections\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end

      resp = Model::PostCourierConnectionsResponse.new
      resp.data = data
      resp.response_header = headers
      resp
    end

    # get_courier_connections_by_id
    # Get courier connection results of a single courier connection.
    # @param id [String] 
    # @param [Hash] opts the optional parameters
    # @return [Model::GetCourierConnectionsByIdResponse]
    def get_courier_connections_by_id(id:, opts: {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: CourierConnectionApi.get_courier_connections_by_id ...'
      end
      if id.nil? or id.to_s == ''
        raise ApiError.new(:error_code => BAD_REQUEST, :message => "id cannot be nil or empty")
      end


      # resource path
      local_var_path = "/tracking/2026-01/courier-connections/#{id}"
      method = :'GET'

      # query parameters
      query_params = opts[:query_params] || {}
      # header parameters
      header_params = opts[:header_params] || {}

      # http body (model)
      post_body = opts[:body]

      # return_type
      return_type = 'CourierConnection'

      new_options = opts.merge(
        :operation => :"CourierConnectionApi.get_courier_connections_by_id",
        :header_params => header_params,
        :query_params => query_params,
        :body => post_body,
        :return_type => return_type
      )

      data, _status_code, headers = @api_client.call_api(method, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: CourierConnectionApi#get_courier_connections_by_id\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end

      resp = Model::GetCourierConnectionsByIdResponse.new
      resp.data = data
      resp.response_header = headers
      resp
    end

    # put_courier_connections_by_id
    # Update a courier connection.
    # @param id [String] 

    # @param body [Model::PutCourierConnectionsByIdRequest]
    # @param [Hash] opts the optional parameters
    # @return [Model::PutCourierConnectionsByIdResponse]
    def put_courier_connections_by_id(id:, body:, opts: {})
      opts[:body] = body
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: CourierConnectionApi.put_courier_connections_by_id ...'
      end
      if id.nil? or id.to_s == ''
        raise ApiError.new(:error_code => BAD_REQUEST, :message => "id cannot be nil or empty")
      end


      # resource path
      local_var_path = "/tracking/2026-01/courier-connections/#{id}"
      method = :'PATCH'

      # query parameters
      query_params = opts[:query_params] || {}
      # header parameters
      header_params = opts[:header_params] || {}

      # http body (model)
      post_body = opts[:body]

      # return_type
      return_type = 'CourierConnection'

      new_options = opts.merge(
        :operation => :"CourierConnectionApi.put_courier_connections_by_id",
        :header_params => header_params,
        :query_params => query_params,
        :body => post_body,
        :return_type => return_type
      )

      data, _status_code, headers = @api_client.call_api(method, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: CourierConnectionApi#put_courier_connections_by_id\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end

      resp = Model::PutCourierConnectionsByIdResponse.new
      resp.data = data
      resp.response_header = headers
      resp
    end

    # delete_courier_connections_by_id
    # Delete a courier connection.
    # @param id [String] 
    # @param [Hash] opts the optional parameters
    # @return [Model::DeleteCourierConnectionsByIdResponse]
    def delete_courier_connections_by_id(id:, opts: {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: CourierConnectionApi.delete_courier_connections_by_id ...'
      end
      if id.nil? or id.to_s == ''
        raise ApiError.new(:error_code => BAD_REQUEST, :message => "id cannot be nil or empty")
      end


      # resource path
      local_var_path = "/tracking/2026-01/courier-connections/#{id}"
      method = :'DELETE'

      # query parameters
      query_params = opts[:query_params] || {}
      # header parameters
      header_params = opts[:header_params] || {}

      # http body (model)
      post_body = opts[:body]

      # return_type
      return_type = 'CourierConnection'

      new_options = opts.merge(
        :operation => :"CourierConnectionApi.delete_courier_connections_by_id",
        :header_params => header_params,
        :query_params => query_params,
        :body => post_body,
        :return_type => return_type
      )

      data, _status_code, headers = @api_client.call_api(method, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: CourierConnectionApi#delete_courier_connections_by_id\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end

      resp = Model::DeleteCourierConnectionsByIdResponse.new
      resp.data = data
      resp.response_header = headers
      resp
    end
  end
end
