# This code was auto generated by AfterShip SDK Generator.
# Do not edit the class manually.
require 'cgi'

module AftershipAPI
  class CourierApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end

    # get_couriers
    # Return a list of couriers.
    # @param [Hash] opts the optional parameters
    # @option opts [Boolean] :active get user activated couriers
    # @option opts [String] :slug Unique courier code Use comma for multiple values. (Example: dhl,ups,usps)
    # @return [Model::GetCouriersResponse]
    def get_couriers(opts: {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: CourierApi.get_couriers ...'
      end


      # resource path
      local_var_path = "/tracking/2026-01/couriers"
      method = :'GET'

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'active'] = opts[:'active'] if !opts[:'active'].nil?
      query_params[:'slug'] = opts[:'slug'] if !opts[:'slug'].nil?
      # header parameters
      header_params = opts[:header_params] || {}

      # http body (model)
      post_body = opts[:body]

      # return_type
      return_type = 'GetCouriersResponseData'

      new_options = opts.merge(
        :operation => :"CourierApi.get_couriers",
        :header_params => header_params,
        :query_params => query_params,
        :body => post_body,
        :return_type => return_type
      )

      data, _status_code, headers = @api_client.call_api(method, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: CourierApi#get_couriers\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end

      resp = Model::GetCouriersResponse.new
      resp.data = data
      resp.response_header = headers
      resp
    end

    # detect_courier
    # Return a list of matched couriers based on tracking number format and  or a list of couriers.

    # @param body [Model::DetectCourierRequest]
    # @param [Hash] opts the optional parameters
    # @return [Model::DetectCourierResponse]
    def detect_courier(body:, opts: {})
      opts[:body] = body
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: CourierApi.detect_courier ...'
      end


      # resource path
      local_var_path = "/tracking/2026-01/couriers/detect"
      method = :'POST'

      # query parameters
      query_params = opts[:query_params] || {}
      # header parameters
      header_params = opts[:header_params] || {}

      # http body (model)
      post_body = opts[:body]

      # return_type
      return_type = 'DetectCourierResponseData'

      new_options = opts.merge(
        :operation => :"CourierApi.detect_courier",
        :header_params => header_params,
        :query_params => query_params,
        :body => post_body,
        :return_type => return_type
      )

      data, _status_code, headers = @api_client.call_api(method, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: CourierApi#detect_courier\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end

      resp = Model::DetectCourierResponse.new
      resp.data = data
      resp.response_header = headers
      resp
    end
  end
end
