# This code was auto generated by AfterShip SDK Generator.
# Do not edit the class manually.
require 'cgi'

module AftershipAPI
  class EstimatedDeliveryDateApi 
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end

    # predict_batch
    # > The estimated delivery date is provided by AfterShip, based on its AI-predictive model. You can display the EDD on the product page, cart, and order checkout page. It indicates when a customer will receive the order.You can use  to activate this feature.Supported functionalities require:1. One `EstimatedDeliveryDate` object for one prediction result.2. Maximum 5 `EstimatedDeliveryDate` objects are allowed.3. API call will fail if any of the requests `EstimatedDeliveryDate` objects do not meet the specification requirement.

    # @param body [Model::PredictBatchRequest] 
    # @param [Hash] opts the optional parameters
    # @return [Model::PredictBatchResponse] 
    def predict_batch(body:,opts: {})
      if "" != ""
        body = {:'' => body}
      end
      opts[:body] = body
      data, _status_code, _headers = predict_batch_with_http_info(opts: opts)
      data
    end

    def predict_batch_with_http_info(opts: {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: EstimatedDeliveryDateApi.predict_batch ...'
      end



      # resource path
      local_var_path = "/tracking/2024-04/estimated-delivery-date/predict-batch" 
      method = :'POST'

      # query parameters
      query_params = opts[:query_params] || {}
      # header parameters
      header_params = opts[:header_params] || {}

      # http body (model)
      post_body = opts[:body]

      # return_type
      return_type = 'PredictBatchResponse'
      
      new_options = opts.merge(
        :operation => :"EstimatedDeliveryDateApi.predict_batch",
        :header_params => header_params,
        :query_params => query_params,
        :body => post_body,
        :return_type => return_type,
        :response_legacy_tag => "",
        :is_paging => false
      )

      data, status_code, headers = @api_client.call_api(method, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: EstimatedDeliveryDateApi#predict_batch\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end 
  end
end