# This code was auto generated by AfterShip SDK Generator.
# Do not edit the class manually.
require 'cgi'

module AftershipAPI
  class EstimatedDeliveryDateApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end

    # predict
    # > The estimated delivery date is provided by AfterShip, based on its AI-predictive model. You can display the EDD on the product page, cart, and order checkout page. It indicates when a customer will receive the order.You can use  to activate this feature.

    # @param body [Model::EstimatedDeliveryDateRequest]
    # @param [Hash] opts the optional parameters
    # @return [Model::PredictResponse]
    def predict(body:, opts: {})
      opts[:body] = body
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: EstimatedDeliveryDateApi.predict ...'
      end


      # resource path
      local_var_path = "/tracking/2026-01/estimated-delivery-date/predict"
      method = :'POST'

      # query parameters
      query_params = opts[:query_params] || {}
      # header parameters
      header_params = opts[:header_params] || {}

      # http body (model)
      post_body = opts[:body]

      # return_type
      return_type = 'EstimatedDeliveryDateResponse'

      new_options = opts.merge(
        :operation => :"EstimatedDeliveryDateApi.predict",
        :header_params => header_params,
        :query_params => query_params,
        :body => post_body,
        :return_type => return_type
      )

      data, _status_code, headers = @api_client.call_api(method, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: EstimatedDeliveryDateApi#predict\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end

      resp = Model::PredictResponse.new
      resp.data = data
      resp.response_header = headers
      resp
    end

    # predict_batch
    # > The estimated delivery date is provided by AfterShip, based on its AI-predictive model. You can display the EDD on the product page, cart, and order checkout page. It indicates when a customer will receive the order.You can use  to activate this feature.Supported functionalities require:1. One `EstimatedDeliveryDate` object for one prediction result.2. Maximum 5 `EstimatedDeliveryDate` objects are allowed.3. API call will fail if any of the requests `EstimatedDeliveryDate` objects do not meet the specification requirement.

    # @param body [Model::PredictBatchRequest]
    # @param [Hash] opts the optional parameters
    # @return [Model::PredictBatchResponse]
    def predict_batch(body:, opts: {})
      opts[:body] = body
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: EstimatedDeliveryDateApi.predict_batch ...'
      end


      # resource path
      local_var_path = "/tracking/2026-01/estimated-delivery-date/predict-batch"
      method = :'POST'

      # query parameters
      query_params = opts[:query_params] || {}
      # header parameters
      header_params = opts[:header_params] || {}

      # http body (model)
      post_body = opts[:body]

      # return_type
      return_type = 'PredictBatchResponseData'

      new_options = opts.merge(
        :operation => :"EstimatedDeliveryDateApi.predict_batch",
        :header_params => header_params,
        :query_params => query_params,
        :body => post_body,
        :return_type => return_type
      )

      data, _status_code, headers = @api_client.call_api(method, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: EstimatedDeliveryDateApi#predict_batch\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end

      resp = Model::PredictBatchResponse.new
      resp.data = data
      resp.response_header = headers
      resp
    end
  end
end
