# This code was auto generated by AfterShip SDK Generator.
# Do not edit the class manually.
# Common files
require 'aftership-tracking-sdk/api_client'
require 'aftership-tracking-sdk/error'
require 'aftership-tracking-sdk/version'
require 'aftership-tracking-sdk/configuration'
require 'aftership-tracking-sdk/sign_string'

# Models
Dir[File.join(__dir__, 'aftership-tracking-sdk/models', '*.rb')].each { |file| require file }

# APIs
Dir[File.join(__dir__, 'aftership-tracking-sdk/api', '*.rb')].each { |file| require file }

module AftershipAPI
  @is_initialized = false

  class << self
    def configure
      config = Configuration.default
      yield(config) if block_given?

      config.check

      if !@is_initialized
        @is_initialized = true
        self.constants.each do |c|
          next unless c[-3..-1] == 'Api'
          attributes = [:attr1]
          wrapper_class = self.const_set(c[0..-4], Struct.new(*attributes))
          original_class = self.const_get(c)

          original_class.public_instance_methods(false).each do |m|
            wrapper_class.class_eval do
              define_singleton_method m do |**arg| 
                original_class.new.send(m, **arg)
              end
            end
          end
        end
      end

      config
    end
  end
end
