# This code was auto generated by AfterShip SDK Generator.
# Do not edit the class manually.
require 'spec_helper'
require 'json'

describe 'Errors' do
  describe 'map codes correctly' do
    it 'contstruct 429 error' do
      err = AftershipAPI::ApiError.new(status_code:400, response_body:'{"meta":{"code":4001,"message":"Invalid JSON format"}}')
      expect(err.error_code).to eql(AftershipAPI::INVALID_JSON)
      expect(err.message).to include('Invalid JSON format')
    end
  end
end
