# This code was auto generated by AfterShip SDK Generator.
# Do not edit the class manually.

module AftershipAPI::Model
  class AdditionalFields
    TRACKING_ACCOUNT_NUMBER = "tracking_account_number".freeze
    DESTINATION_POSTAL_CODE = "destination_postal_code".freeze
    DESTINATION_STATE = "destination_state".freeze
    TRACKING_KEY = "tracking_key".freeze
    ORIGIN_COUNTRY_REGION = "origin_country_region".freeze
    DESTINATION_COUNTRY_REGION = "destination_country_region".freeze
    TRACKING_SHIP_DATE = "tracking_ship_date".freeze
    def self.all_vars
      @all_vars ||= [TRACKING_ACCOUNT_NUMBER,DESTINATION_POSTAL_CODE,DESTINATION_STATE,TRACKING_KEY,ORIGIN_COUNTRY_REGION,DESTINATION_COUNTRY_REGION,TRACKING_SHIP_DATE,].freeze
    end

    # Builds the enum from string
    # @param value [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param value [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if AdditionalFields.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #AdditionalFields"
    end
  end
end
