# This code was auto generated by AfterShip SDK Generator.
# Do not edit the class manually.
module AftershipAPI::Model
  class DetectCourierResponse
    attr_accessor :response_header
    # data: DetectCourierResponseData
    attr_accessor :data
  end
end
