# This code was auto generated by AfterShip SDK Generator.
# Do not edit the class manually.
module AftershipAPI::Model
  class GetTrackingsResponse
    attr_accessor :response_header
    # data: GetTrackingsResponseData
    attr_accessor :data
  end
end
