# This code was auto generated by AfterShip SDK Generator.
# Do not edit the class manually.
module AftershipAPI::Model
  class GetCourierConnectionsResponse
    attr_accessor :response_header
    # data: GetCourierConnectionsResponseData
    attr_accessor :data
  end
end
