# This code was auto generated by AfterShip SDK Generator.
# Do not edit the class manually.
module AftershipAPI::Model
  class GetCouriersResponse
    attr_accessor :response_header
    # data: GetCouriersResponseData
    attr_accessor :data
  end
end
