# This code was auto generated by AfterShip SDK Generator.
# Do not edit the class manually.
module AftershipAPI::Model
  class MarkTrackingCompletedByIdRequestReason
    DELIVERED = "DELIVERED".freeze
    LOST = "LOST".freeze
    RETURNED_TO_SENDER = "RETURNED_TO_SENDER".freeze
    def self.all_vars
      @all_vars ||= [DELIVERED, LOST, RETURNED_TO_SENDER,].freeze
    end

    # Builds the enum from string
    # @param value [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param value [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if MarkTrackingCompletedByIdRequestReason.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #MarkTrackingCompletedByIdRequestReason"
    end
  end
end
