# This code was auto generated by AfterShip SDK Generator.
# Do not edit the class manually.
module AftershipAPI::Model
  class MarkTrackingCompletedByIdResponse
    attr_accessor :response_header
    # data: Tracking
    attr_accessor :data
  end
end
