# This code was auto generated by AfterShip SDK Generator.
# Do not edit the class manually.
module AftershipAPI::Model
  class MetaType
    BAD_REQUEST = "BadRequest".freeze
    UNAUTHORIZED = "Unauthorized".freeze
    FORBIDDEN = "Forbidden".freeze
    NOT_FOUND = "NotFound".freeze
    TOO_MANY_REQUESTS = "TooManyRequests".freeze
    INTERNAL_ERROR = "InternalError".freeze
    def self.all_vars
      @all_vars ||= [BAD_REQUEST, UNAUTHORIZED, FORBIDDEN, NOT_FOUND, TOO_MANY_REQUESTS, INTERNAL_ERROR,].freeze
    end

    # Builds the enum from string
    # @param value [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param value [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if MetaType.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #MetaType"
    end
  end
end
