# This code was auto generated by AfterShip SDK Generator.
# Do not edit the class manually.
module AftershipAPI::Model
  class PredictResponse
    attr_accessor :response_header
    # data: EstimatedDeliveryDateResponse
    attr_accessor :data
  end
end
