# This code was auto generated by AfterShip SDK Generator.
# Do not edit the class manually.
module AftershipAPI::Model
  class PredictBatchResponse
    attr_accessor :response_header
    # data: PredictBatchResponseData
    attr_accessor :data
  end
end
