# This code was auto generated by AfterShip SDK Generator.
# Do not edit the class manually.
module AftershipAPI::Model
  class PutCourierConnectionsByIdResponse
    attr_accessor :response_header
    # data: CourierConnection
    attr_accessor :data
  end
end
