# This code was auto generated by AfterShip SDK Generator.
# Do not edit the class manually.

module AftershipAPI::Model
  class SlugGroupV1
    AMAZON_GROUP = "amazon-group".freeze
    FEDEX_GROUP = "fedex-group".freeze
    TOLL_GROUP = "toll-group".freeze
    TAQBIN_GROUP = "taqbin-group".freeze
    TNT_GROUP = "tnt-group".freeze
    CJ_GROUP = "cj-group".freeze
    HERMES_GROUP = "hermes-group".freeze
    DPD_GROUP = "dpd-group".freeze
    GLS_GROUP = "gls-group".freeze
    DHL_GROUP = "dhl-group".freeze
    FASTWAY_GROUP = "fastway-group".freeze
    ASENDIA_GROUP = "asendia-group".freeze
    def self.all_vars
      @all_vars ||= [AMAZON_GROUP,FEDEX_GROUP,TOLL_GROUP,TAQBIN_GROUP,TNT_GROUP,CJ_GROUP,HERMES_GROUP,DPD_GROUP,GLS_GROUP,DHL_GROUP,FASTWAY_GROUP,ASENDIA_GROUP,].freeze
    end

    # Builds the enum from string
    # @param value [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param value [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if SlugGroupV1.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #SlugGroupV1"
    end
  end
end
