# This code was auto generated by AfterShip SDK Generator.
# Do not edit the class manually.
module AftershipAPI::Model
  class Tag
    PENDING = "Pending".freeze
    INFO_RECEIVED = "InfoReceived".freeze
    IN_TRANSIT = "InTransit".freeze
    OUT_FOR_DELIVERY = "OutForDelivery".freeze
    ATTEMPT_FAIL = "AttemptFail".freeze
    DELIVERED = "Delivered".freeze
    AVAILABLE_FOR_PICKUP = "AvailableForPickup".freeze
    EXCEPTION = "Exception".freeze
    EXPIRED = "Expired".freeze
    def self.all_vars
      @all_vars ||= [PENDING, INFO_RECEIVED, IN_TRANSIT, OUT_FOR_DELIVERY, ATTEMPT_FAIL, DELIVERED, AVAILABLE_FOR_PICKUP, EXCEPTION, EXPIRED,].freeze
    end

    # Builds the enum from string
    # @param value [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param value [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if Tag.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #Tag"
    end
  end
end
