# This code was auto generated by AfterShip SDK Generator.
# Do not edit the class manually.

module AftershipAPI::Model
  class TagV1
    PENDING = "Pending".freeze
    INFORECEIVED = "InfoReceived".freeze
    INTRANSIT = "InTransit".freeze
    OUTFORDELIVERY = "OutForDelivery".freeze
    ATTEMPTFAIL = "AttemptFail".freeze
    DELIVERED = "Delivered".freeze
    AVAILABLEFORPICKUP = "AvailableForPickup".freeze
    EXCEPTION = "Exception".freeze
    EXPIRED = "Expired".freeze
    def self.all_vars
      @all_vars ||= [PENDING, INFORECEIVED, INTRANSIT, OUTFORDELIVERY, ATTEMPTFAIL, DELIVERED, AVAILABLEFORPICKUP, EXCEPTION, EXPIRED,].freeze
    end

    # Builds the enum from string
    # @param value [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param value [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if TagV1.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #TagV1"
    end
  end
end
