# This code was auto generated by AfterShip SDK Generator.
# Do not edit the class manually.
module AftershipAPI::Model
  class TrackingLastMileSource
    SYSTEM = "system".freeze
    USER = "user".freeze
    def self.all_vars
      @all_vars ||= [SYSTEM, USER,].freeze
    end

    # Builds the enum from string
    # @param value [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param value [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if TrackingLastMileSource.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #TrackingLastMileSource"
    end
  end
end
