# This code was auto generated by AfterShip SDK Generator.
# Do not edit the class manually.
module AftershipAPI::Model
  class TrackingMultiPieceInfoType
    MASTER = "master".freeze
    CHILD = "child".freeze
    def self.all_vars
      @all_vars ||= [MASTER, CHILD,].freeze
    end

    # Builds the enum from string
    # @param value [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param value [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if TrackingMultiPieceInfoType.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #TrackingMultiPieceInfoType"
    end
  end
end
