# This code was auto generated by AfterShip SDK Generator.
# Do not edit the class manually.
module AftershipAPI::Model
  class TrackingLatestEstimatedDeliverySource
    CARRIER_EDD = "Carrier EDD".freeze
    AFTER_SHIP_EDD = "AfterShip EDD".freeze
    CUSTOM_EDD = "Custom EDD".freeze
    ORDER_EDD = "Order EDD".freeze
    def self.all_vars
      @all_vars ||= [CARRIER_EDD, AFTER_SHIP_EDD, CUSTOM_EDD, ORDER_EDD,].freeze
    end

    # Builds the enum from string
    # @param value [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param value [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if TrackingLatestEstimatedDeliverySource.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #TrackingLatestEstimatedDeliverySource"
    end
  end
end
