# This code was auto generated by AfterShip SDK Generator.
# Do not edit the class manually.
module AftershipAPI::Model
  class TrackingSignatureRequirement
    SIGNATURE_REQUIRED = "signature_required".freeze
    ADULT_SIGNATURE_REQUIRED = "adult_signature_required".freeze
    INDIRECT_SIGNATURE_REQUIRED = "indirect_signature_required".freeze
    NO_SIGNATURE_REQUIRED = "no_signature_required".freeze
    NULL = "null".freeze
    def self.all_vars
      @all_vars ||= [SIGNATURE_REQUIRED, ADULT_SIGNATURE_REQUIRED, INDIRECT_SIGNATURE_REQUIRED, NO_SIGNATURE_REQUIRED, NULL,].freeze
    end

    # Builds the enum from string
    # @param value [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param value [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if TrackingSignatureRequirement.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #TrackingSignatureRequirement"
    end
  end
end
