# This code was auto generated by AfterShip SDK Generator.
# Do not edit the class manually.
module AftershipAPI::Model
  class TrackingLatestEstimatedDeliveryType
    RANGE = "range".freeze
    SPECIFIC = "specific".freeze
    def self.all_vars
      @all_vars ||= [RANGE, SPECIFIC,].freeze
    end

    # Builds the enum from string
    # @param value [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param value [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if TrackingLatestEstimatedDeliveryType.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #TrackingLatestEstimatedDeliveryType"
    end
  end
end
