# This code was auto generated by AfterShip SDK Generator.
# Do not edit the class manually.
module AftershipAPI::Model
  class UpdateTrackingByIdRequestDeliveryType
    PICKUP_AT_STORE = "pickup_at_store".freeze
    PICKUP_AT_COURIER = "pickup_at_courier".freeze
    DOOR_TO_DOOR = "door_to_door".freeze
    def self.all_vars
      @all_vars ||= [PICKUP_AT_STORE, PICKUP_AT_COURIER, DOOR_TO_DOOR,].freeze
    end

    # Builds the enum from string
    # @param value [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param value [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if UpdateTrackingByIdRequestDeliveryType.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #UpdateTrackingByIdRequestDeliveryType"
    end
  end
end
